{"name": "Login to Orange HRM web page with parameters -- @1.4 ", "status": "failed", "statusDetails": {"message": "AssertionError: '/dashboard/index' not found in 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' : Test case 2 fail\n", "trace": "  File \"C:\\Users\\sheel\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\sheel\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_step.py\", line 59, in step_login_success\n    testorange_hrm.assertIn(\"/dashboard/index\", dashboard_url,  \"Test case 2 fail\")\n  File \"C:\\Users\\sheel\\Lib\\unittest\\case.py\", line 1140, in assertIn\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"C:\\Users\\sheel\\Lib\\unittest\\case.py\", line 703, in fail\n    raise self.failureException(msg)\n"}, "steps": [{"name": "Given User has launched Chrome Browser", "status": "passed", "start": 1689774458122, "stop": 1689774460721}, {"name": "When the User has navigate to the Orange HRM login page", "status": "passed", "start": 1689774460721, "stop": 1689774462535}, {"name": "When the User enters valid \"sdmfn\" and \"dfsbnn\"", "status": "passed", "start": 1689774462535, "stop": 1689774463302}, {"name": "Then the User should successfully login", "status": "failed", "statusDetails": {"message": "AssertionError: '/dashboard/index' not found in 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' : Test case 2 fail\n", "trace": "  File \"C:\\Users\\sheel\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\sheel\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_step.py\", line 59, in step_login_success\n    testorange_hrm.assertIn(\"/dashboard/index\", dashboard_url,  \"Test case 2 fail\")\n  File \"C:\\Users\\sheel\\Lib\\unittest\\case.py\", line 1140, in assertIn\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"C:\\Users\\sheel\\Lib\\unittest\\case.py\", line 703, in fail\n    raise self.failureException(msg)\n"}, "start": 1689774463302, "stop": 1689774463954}], "parameters": [{"name": "username", "value": "sdmfn"}, {"name": "password", "value": "dfsbnn"}], "start": 1689774458121, "stop": 1689774466022, "uuid": "d152a23a-32a1-4ef6-8c00-96158dd1aac2", "historyId": "48dcb7ea89d69db2017245b6dacaefde", "fullName": "Login feature of Orange HRM website: Login to Orange HRM web page with parameters", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "runsecond"}, {"name": "tag", "value": "tag"}, {"name": "feature", "value": "Login feature of Orange HRM website"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}