{"name": "Login to Orange HRM web page with parameters -- @1.3 ", "status": "failed", "statusDetails": {"message": "AssertionError: '/dashboard/index' not found in 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' : Test case 2 fail\n", "trace": "  File \"C:\\Users\\sheel\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\sheel\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_step.py\", line 59, in step_login_success\n    testorange_hrm.assertIn(\"/dashboard/index\", dashboard_url,  \"Test case 2 fail\")\n  File \"C:\\Users\\sheel\\Lib\\unittest\\case.py\", line 1140, in assertIn\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"C:\\Users\\sheel\\Lib\\unittest\\case.py\", line 703, in fail\n    raise self.failureException(msg)\n"}, "steps": [{"name": "Given User has launched Chrome Browser", "status": "passed", "start": 1689774449196, "stop": 1689774452390}, {"name": "When the User has navigate to the Orange HRM login page", "status": "passed", "start": 1689774452390, "stop": 1689774454271}, {"name": "When the User enters valid \"dfdsf\" and \"admin123\"", "status": "passed", "start": 1689774454271, "stop": 1689774455392}, {"name": "Then the User should successfully login", "status": "failed", "statusDetails": {"message": "AssertionError: '/dashboard/index' not found in 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' : Test case 2 fail\n", "trace": "  File \"C:\\Users\\sheel\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\sheel\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_step.py\", line 59, in step_login_success\n    testorange_hrm.assertIn(\"/dashboard/index\", dashboard_url,  \"Test case 2 fail\")\n  File \"C:\\Users\\sheel\\Lib\\unittest\\case.py\", line 1140, in assertIn\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"C:\\Users\\sheel\\Lib\\unittest\\case.py\", line 703, in fail\n    raise self.failureException(msg)\n"}, "start": 1689774455392, "stop": 1689774456023}], "parameters": [{"name": "username", "value": "dfdsf"}, {"name": "password", "value": "admin123"}], "start": 1689774449195, "stop": 1689774458120, "uuid": "5a0fc3cc-16a7-44bd-bb24-a64c1811be40", "historyId": "85a7bfd1d8180877903040a3c3fbae43", "fullName": "Login feature of Orange HRM website: Login to Orange HRM web page with parameters", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "runsecond"}, {"name": "tag", "value": "tag"}, {"name": "feature", "value": "Login feature of Orange HRM website"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}