{"name": "Login to Orange HRM web page with parameters -- @1.2 ", "status": "failed", "statusDetails": {"message": "AssertionError: '/dashboard/index' not found in 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' : Test case 2 fail\n", "trace": "  File \"C:\\Users\\sheel\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\sheel\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_step.py\", line 59, in step_login_success\n    testorange_hrm.assertIn(\"/dashboard/index\", dashboard_url,  \"Test case 2 fail\")\n  File \"C:\\Users\\sheel\\Lib\\unittest\\case.py\", line 1140, in assertIn\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"C:\\Users\\sheel\\Lib\\unittest\\case.py\", line 703, in fail\n    raise self.failureException(msg)\n"}, "steps": [{"name": "Given User has launched Chrome Browser", "status": "passed", "start": 1689734949183, "stop": 1689734951892}, {"name": "When the User has navigate to the Orange HRM login page", "status": "passed", "start": 1689734951892, "stop": 1689734953780}, {"name": "When the User enters valid \"Admin\" and \"shjsdd\"", "status": "passed", "start": 1689734953780, "stop": 1689734954578}, {"name": "Then the User should successfully login", "status": "failed", "statusDetails": {"message": "AssertionError: '/dashboard/index' not found in 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' : Test case 2 fail\n", "trace": "  File \"C:\\Users\\sheel\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\sheel\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_step.py\", line 59, in step_login_success\n    testorange_hrm.assertIn(\"/dashboard/index\", dashboard_url,  \"Test case 2 fail\")\n  File \"C:\\Users\\sheel\\Lib\\unittest\\case.py\", line 1140, in assertIn\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"C:\\Users\\sheel\\Lib\\unittest\\case.py\", line 703, in fail\n    raise self.failureException(msg)\n"}, "start": 1689734954579, "stop": 1689734955497}], "parameters": [{"name": "username", "value": "Admin"}, {"name": "password", "value": "shjsdd"}], "start": 1689734949181, "stop": 1689734958619, "uuid": "5749a01a-1d96-44ae-95d9-850b2368c38c", "historyId": "b579b4ae4f80accc726d4a24c5bb71cc", "fullName": "Login feature of Orange HRM website: Login to Orange HRM web page with parameters", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "runsecond"}, {"name": "tag", "value": "tag"}, {"name": "feature", "value": "Login feature of Orange HRM website"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}